{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-events/2.3.12/ktor-events-2.3.12.module",
    "group": "io.ktor",
    "module": "ktor-events",
    "version": "2.3.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.7.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-events-jvm-2.3.12.jar",
          "url": "ktor-events-jvm-2.3.12.jar",
          "size": 7397,
          "sha512": "068f15a1314d9ae218a769a7f3658cd5716f5146db7bc6eb85c27e658e7e685869ef4661056dc9ab024061ef41818f38f123454101d5994ace073aab641dfc3f",
          "sha256": "44f0b1de6b0947182d25408d1101c56cf8c01a7b809ee0152bd81d9adc9aa576",
          "sha1": "d8f19c13700f04027436fb42ac5458e305b81423",
          "md5": "4aa20065903e308418c8ad72edf538a2"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.7.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-events-jvm-2.3.12.jar",
          "url": "ktor-events-jvm-2.3.12.jar",
          "size": 7397,
          "sha512": "068f15a1314d9ae218a769a7f3658cd5716f5146db7bc6eb85c27e658e7e685869ef4661056dc9ab024061ef41818f38f123454101d5994ace073aab641dfc3f",
          "sha256": "44f0b1de6b0947182d25408d1101c56cf8c01a7b809ee0152bd81d9adc9aa576",
          "sha1": "d8f19c13700f04027436fb42ac5458e305b81423",
          "md5": "4aa20065903e308418c8ad72edf538a2"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ktor-events-jvm-2.3.12-sources.jar",
          "url": "ktor-events-jvm-2.3.12-sources.jar",
          "size": 2072,
          "sha512": "bc8c4431ea49a7b97661e5cf00070e7ddd15bc86fe0c2c63dbde4b1d91198f1b077aed0d451c029337324faa54f322e49b0751cd19eb17d3398f25ddfa2810f5",
          "sha256": "1213d03731e0504ef9fd04ae0333c33f9352b1cac59697bd698aa0b37aacc5de",
          "sha1": "14a9cb45d01c0c8d5a8c2f2c150f5f6534cf5aee",
          "md5": "3be695501cd7f07a54b716e3a7b1a02d"
        }
      ]
    }
  ]
}
