{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-serialization/2.3.12/ktor-serialization-2.3.12.module",
    "group": "io.ktor",
    "module": "ktor-serialization",
    "version": "2.3.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.7.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-websockets",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-serialization-jvm-2.3.12.jar",
          "url": "ktor-serialization-jvm-2.3.12.jar",
          "size": 24738,
          "sha512": "2d613ea551407aaf11b1f897e8c30dca3123a8374e490e437341a7171919ffa6aee2c3f7a01cb2072f54e05b14a125f0463a7115b7d63604d13ff94712b43f69",
          "sha256": "0e05534fbc3b0941127b6ef39e705c34c367dae8b0a08290701c60e97e88fa72",
          "sha1": "81e9bbd2417193ff23b0e2a89e383e78083fbad0",
          "md5": "2ac340dee787d8502f6f6738472b5e1d"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.7.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-websockets",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-serialization-jvm-2.3.12.jar",
          "url": "ktor-serialization-jvm-2.3.12.jar",
          "size": 24738,
          "sha512": "2d613ea551407aaf11b1f897e8c30dca3123a8374e490e437341a7171919ffa6aee2c3f7a01cb2072f54e05b14a125f0463a7115b7d63604d13ff94712b43f69",
          "sha256": "0e05534fbc3b0941127b6ef39e705c34c367dae8b0a08290701c60e97e88fa72",
          "sha1": "81e9bbd2417193ff23b0e2a89e383e78083fbad0",
          "md5": "2ac340dee787d8502f6f6738472b5e1d"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ktor-serialization-jvm-2.3.12-sources.jar",
          "url": "ktor-serialization-jvm-2.3.12-sources.jar",
          "size": 3629,
          "sha512": "49fe12b9539306c0695c4e3271e3cfdf7e904d91a665eb256cc0f86c6b3c78e5b27a1bfedf51172a4d915f2a3e9daa0bfdc412ebef511edef268ae03566ab6ce",
          "sha256": "051d868621eaea7fcad8286bc90742ebca6b31f3f0759318850c3df3c138b3b7",
          "sha1": "85a50d9fd68216cc09f00bc3f88e87785c21613c",
          "md5": "f598d58db690f0b956deff64e9df7841"
        }
      ]
    }
  ]
}
