version: "3.9"

x-jira-env: &jira-db
  ATL_JDBC_URL: jdbc:postgresql://postgres:5432/jira
  ATL_JDBC_USER: jira
  ATL_JDBC_PASSWORD: jira
  ATL_DB_TYPE: postgresql

services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_DB: jira
      POSTGRES_USER: jira
      POSTGRES_PASSWORD: jira
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres-data:/var/lib/postgresql/data

  jira:
    image: atlassian/jira-software:9.17.0
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    restart: unless-stopped
    environment:
      <<: *jira-db
      ATL_PROXY_NAME: localhost
      ATL_PROXY_PORT: 8080
      ATL_TOMCAT_PORT: 8080
    volumes:
      - jira-home:/var/atlassian/application-data/jira
      - jira-logs:/opt/atlassian/jira/logs

  jira-cli:
    image: ghcr.io/ankitpokhrel/jira-cli:latest
    depends_on:
      jira:
        condition: service_started
    environment:
      JIRA_SERVER: http://jira:8080
      JIRA_USER_EMAIL: ${JIRA_USER_EMAIL:-user@example.com}
      JIRA_API_TOKEN: ${JIRA_API_TOKEN:-changeme}
    working_dir: /workspace
    volumes:
      - ./:/workspace
    entrypoint: ["jira"]
    command: ["version"]
    stdin_open: true
    tty: true

volumes:
  postgres-data:
  jira-home:
  jira-logs:
