{
  "formatVersion": "1.1",
  "component": {
    "group": "io.ktor",
    "module": "ktor-http",
    "version": "2.3.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.19.0"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-http-metadata-2.3.12.jar",
          "url": "ktor-http-2.3.12.jar",
          "size": 33670,
          "sha512": "5d775000b16eabdf66761d543a09de4262177593ccbd3c0290353ecb22a1811c323a19010804ea2b1382b1f7395fc55c48664a6baefedacae9b25d571e7f7c7a",
          "sha256": "d915517e25c4e5f78c50fd18837b70b4629b850eec5e64f3e4617c263e68bdb7",
          "sha1": "3b4652dc0beb2d3ad9f5a91525d72953263e46ff",
          "md5": "9a54f148e85205b26d10d46384d7c3e7"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "ktor-http-kotlin-2.3.12-sources.jar",
          "url": "ktor-http-2.3.12-sources.jar",
          "size": 80211,
          "sha512": "ad16b2c2e6a89f2ffd7b9f21478c61f98d992bc331e658826501212689d24e642c5c85b6304c0185809bfaa97b2473ff3b0331e7703473c418d04ad398c4a9db",
          "sha256": "2940af2115eb0d992650cc9cc78f33528fa443ec6757a396e571cadb252a79a9",
          "sha1": "c267d21c1e026aabca26dd8922d602854158fdf7",
          "md5": "c6a67f1c941fe5531c6e0022d6cc7285"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-iosarm64/2.3.12/ktor-http-iosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-http-iosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-iosarm64/2.3.12/ktor-http-iosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-http-iosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-iosarm64/2.3.12/ktor-http-iosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-http-iosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-iossimulatorarm64/2.3.12/ktor-http-iossimulatorarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-http-iossimulatorarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-iossimulatorarm64/2.3.12/ktor-http-iossimulatorarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-http-iossimulatorarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-iossimulatorarm64/2.3.12/ktor-http-iossimulatorarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-http-iossimulatorarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-iosx64/2.3.12/ktor-http-iosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-http-iosx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-iosx64/2.3.12/ktor-http-iosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-http-iosx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-iosx64/2.3.12/ktor-http-iosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-http-iosx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktor-http-js/2.3.12/ktor-http-js-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-http-js",
        "version": "2.3.12"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktor-http-js/2.3.12/ktor-http-js-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-http-js",
        "version": "2.3.12"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktor-http-js/2.3.12/ktor-http-js-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-http-js",
        "version": "2.3.12"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-http-jvm/2.3.12/ktor-http-jvm-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-http-jvm",
        "version": "2.3.12"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-http-jvm/2.3.12/ktor-http-jvm-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-http-jvm",
        "version": "2.3.12"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-http-jvm/2.3.12/ktor-http-jvm-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-http-jvm",
        "version": "2.3.12"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-linuxarm64/2.3.12/ktor-http-linuxarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-http-linuxarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-linuxarm64/2.3.12/ktor-http-linuxarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-http-linuxarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-linuxx64/2.3.12/ktor-http-linuxx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-http-linuxx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-linuxx64/2.3.12/ktor-http-linuxx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-http-linuxx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-macosarm64/2.3.12/ktor-http-macosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-http-macosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-macosarm64/2.3.12/ktor-http-macosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-http-macosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-macosarm64/2.3.12/ktor-http-macosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-http-macosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-macosx64/2.3.12/ktor-http-macosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-http-macosx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-macosx64/2.3.12/ktor-http-macosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-http-macosx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-macosx64/2.3.12/ktor-http-macosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-http-macosx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-mingwx64/2.3.12/ktor-http-mingwx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-http-mingwx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-mingwx64/2.3.12/ktor-http-mingwx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-http-mingwx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-tvosarm64/2.3.12/ktor-http-tvosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-http-tvosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-tvosarm64/2.3.12/ktor-http-tvosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-http-tvosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-tvosarm64/2.3.12/ktor-http-tvosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-http-tvosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-tvossimulatorarm64/2.3.12/ktor-http-tvossimulatorarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-http-tvossimulatorarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-tvossimulatorarm64/2.3.12/ktor-http-tvossimulatorarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-http-tvossimulatorarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-tvossimulatorarm64/2.3.12/ktor-http-tvossimulatorarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-http-tvossimulatorarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-tvosx64/2.3.12/ktor-http-tvosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-http-tvosx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-tvosx64/2.3.12/ktor-http-tvosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-http-tvosx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-tvosx64/2.3.12/ktor-http-tvosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-http-tvosx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-watchosarm32/2.3.12/ktor-http-watchosarm32-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-http-watchosarm32",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-watchosarm32/2.3.12/ktor-http-watchosarm32-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-http-watchosarm32",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-watchosarm32/2.3.12/ktor-http-watchosarm32-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-http-watchosarm32",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-watchosarm64/2.3.12/ktor-http-watchosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-http-watchosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-watchosarm64/2.3.12/ktor-http-watchosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-http-watchosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-watchosarm64/2.3.12/ktor-http-watchosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-http-watchosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-watchossimulatorarm64/2.3.12/ktor-http-watchossimulatorarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-http-watchossimulatorarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-watchossimulatorarm64/2.3.12/ktor-http-watchossimulatorarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-http-watchossimulatorarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-watchossimulatorarm64/2.3.12/ktor-http-watchossimulatorarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-http-watchossimulatorarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-watchosx64/2.3.12/ktor-http-watchosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-http-watchosx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-watchosx64/2.3.12/ktor-http-watchosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-http-watchosx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-http-watchosx64/2.3.12/ktor-http-watchosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-http-watchosx64",
        "version": "2.3.12"
      }
    }
  ]
}
