{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-network-tls/2.3.12/ktor-network-tls-2.3.12.module",
    "group": "io.ktor",
    "module": "ktor-network-tls",
    "version": "2.3.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.7.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-network",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "2.3.12"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-network-tls-jvm-2.3.12.jar",
          "url": "ktor-network-tls-jvm-2.3.12.jar",
          "size": 208505,
          "sha512": "331b25a74d9c94df705b02e55949639377600346bd82d227e793204cdd1d2ec252b6f38ae3c08a475aebcb19d98ce60ebf180718ebda2928a0bb629a1a6ee572",
          "sha256": "2b74bf6a17776658520106de5137df9dc35df8ac1ed01624f83409962d128a75",
          "sha1": "fed673b17e27ff55625a087e59497e3931f8ab8a",
          "md5": "954231771ef6ea4a0648079e4ba651ac"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.7.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-network",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "2.3.12"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-network-tls-jvm-2.3.12.jar",
          "url": "ktor-network-tls-jvm-2.3.12.jar",
          "size": 208505,
          "sha512": "331b25a74d9c94df705b02e55949639377600346bd82d227e793204cdd1d2ec252b6f38ae3c08a475aebcb19d98ce60ebf180718ebda2928a0bb629a1a6ee572",
          "sha256": "2b74bf6a17776658520106de5137df9dc35df8ac1ed01624f83409962d128a75",
          "sha1": "fed673b17e27ff55625a087e59497e3931f8ab8a",
          "md5": "954231771ef6ea4a0648079e4ba651ac"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ktor-network-tls-jvm-2.3.12-sources.jar",
          "url": "ktor-network-tls-jvm-2.3.12-sources.jar",
          "size": 37779,
          "sha512": "05a8ab94e6800260e7845bb68fe8ecbc467d14a9a8106f5ca1c820ccea9f007d552db283b69fbc8f08d8cfdb3d941c5b988a616bdb7fa6fc2e0441e5ac62e4e8",
          "sha256": "dad34e5d3cd17da6b4719d62f828267efda6fc9743ae28582ea253bba83fb263",
          "sha1": "412ee6e52f00c29b82a119507e7b286031fb2488",
          "md5": "6ef63cf31cf17046f487c151d48c324f"
        }
      ]
    }
  ]
}
