{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-client-content-negotiation/2.3.12/ktor-client-content-negotiation-2.3.12.module",
    "group": "io.ktor",
    "module": "ktor-client-content-negotiation",
    "version": "2.3.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.7.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-content-negotiation-jvm-2.3.12.jar",
          "url": "ktor-client-content-negotiation-jvm-2.3.12.jar",
          "size": 27402,
          "sha512": "1df4196d8ed969e48200c1c8b43a86201425fe13c65ab522ca3303a4d99bc58427cde91d908ad5d1ecf9e9144dae2629e7a5c96c5687b637cb6b54b6a03e2f97",
          "sha256": "b65290ac100096363d01ea71027d970cec6a48d076b6e4b36de1cae2c183cd72",
          "sha1": "3272464ff169ce8452cf59f953b8ae664d0bb716",
          "md5": "3dce595673c2bcc8fd1f741bbf1c030a"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.7.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-content-negotiation-jvm-2.3.12.jar",
          "url": "ktor-client-content-negotiation-jvm-2.3.12.jar",
          "size": 27402,
          "sha512": "1df4196d8ed969e48200c1c8b43a86201425fe13c65ab522ca3303a4d99bc58427cde91d908ad5d1ecf9e9144dae2629e7a5c96c5687b637cb6b54b6a03e2f97",
          "sha256": "b65290ac100096363d01ea71027d970cec6a48d076b6e4b36de1cae2c183cd72",
          "sha1": "3272464ff169ce8452cf59f953b8ae664d0bb716",
          "md5": "3dce595673c2bcc8fd1f741bbf1c030a"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ktor-client-content-negotiation-jvm-2.3.12-sources.jar",
          "url": "ktor-client-content-negotiation-jvm-2.3.12-sources.jar",
          "size": 5017,
          "sha512": "e2f53d76050e0b7d678c0bbf1a259d19210854df9df034346fb0a1bab040949e626641545e26b9178bbe67994106c57e8327b02898c87bfd903dd340f9cb769b",
          "sha256": "ad7f0c6a8824d25983d8fcd1f8d1252dbc8c29ec8c72e17737921e13fe8fa737",
          "sha1": "6727548d6f1846c35f6bbbd40f749fb53ad5e83c",
          "md5": "d0ed2cd28deed8c984406a35e4d34744"
        }
      ]
    }
  ]
}
