{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-utils/2.3.12/ktor-utils-2.3.12.module",
    "group": "io.ktor",
    "module": "ktor-utils",
    "version": "2.3.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.7.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-io",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-utils-jvm-2.3.12.jar",
          "url": "ktor-utils-jvm-2.3.12.jar",
          "size": 335964,
          "sha512": "e2c783d27bfe8416ab055b3584593bb59f3e7ae4d9bf1116a2fcd15dcd90aae2c3eeb148b90b06c6062cd94aff45295c5c4b2a1c9475571cf4f67025fc4cfef7",
          "sha256": "6a72d6867330065ed461952fff19ea55ba844352f748cec1872f5bc7b21efc02",
          "sha1": "7cb89952751d184b60f9c312b70842e75c01bf44",
          "md5": "37b09af08940b0a3f01f8631a34645f7"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.7.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-io",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-utils-jvm-2.3.12.jar",
          "url": "ktor-utils-jvm-2.3.12.jar",
          "size": 335964,
          "sha512": "e2c783d27bfe8416ab055b3584593bb59f3e7ae4d9bf1116a2fcd15dcd90aae2c3eeb148b90b06c6062cd94aff45295c5c4b2a1c9475571cf4f67025fc4cfef7",
          "sha256": "6a72d6867330065ed461952fff19ea55ba844352f748cec1872f5bc7b21efc02",
          "sha1": "7cb89952751d184b60f9c312b70842e75c01bf44",
          "md5": "37b09af08940b0a3f01f8631a34645f7"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ktor-utils-jvm-2.3.12-sources.jar",
          "url": "ktor-utils-jvm-2.3.12-sources.jar",
          "size": 82921,
          "sha512": "db80e6098e3668d4a31e1d243b3de2b5b3ff7ae48b5de497207c759468b5362abdc2f88f26af04f0653393ffee5c8df905b32ea85d7b090869dad5f0b9fe9a47",
          "sha256": "867396d4a591973908576f8be96894278f5e03e829d30cc76bc92ab0d30e1887",
          "sha1": "987b8d306734fa986cc8d014c546d79db8746370",
          "md5": "7e23d7effd2a0f2bf2a3511845085b37"
        }
      ]
    }
  ]
}
