{
  "formatVersion": "1.1",
  "component": {
    "group": "io.ktor",
    "module": "ktor-client-content-negotiation",
    "version": "2.3.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.19.0"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-content-negotiation-metadata-2.3.12.jar",
          "url": "ktor-client-content-negotiation-2.3.12.jar",
          "size": 10607,
          "sha512": "67df6578ce8efe47e86f93a4745f74c1257b702cfe00430bb5ecd4c4ddd31260f69c22aa3e28586d45b89ae77c0dcf294a1fa2344adb609a53e1dbe0b4c5d725",
          "sha256": "024dc7dd377b397c1783b2c36c9790f016156e98731843f5a6139cf28dee3fbd",
          "sha1": "db2245e2ea6a05088c5c7e62939790c068cd7a4b",
          "md5": "8c1e2d0ebe45dcb1e3b96595a514ae5f"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "ktor-client-content-negotiation-kotlin-2.3.12-sources.jar",
          "url": "ktor-client-content-negotiation-2.3.12-sources.jar",
          "size": 5004,
          "sha512": "b4e7d0e10d57c2e6c290c0a9a656c1120540b5d24ef25f0c81abe68031485c674d197117dfb340717bab59e13c93ff97c275168869a574b2c9d4775452ce5122",
          "sha256": "624c25810b8d92d20a1166643f27dad85a967ed2badbcf9e9aca62f1bde9e149",
          "sha1": "976a2a6735d1cd49d441f442e8814cff3e485820",
          "md5": "24d7674deb9b83f1f2c621eb6e2ca469"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-iosarm64/2.3.12/ktor-client-content-negotiation-iosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-iosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-iosarm64/2.3.12/ktor-client-content-negotiation-iosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-iosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-iosarm64/2.3.12/ktor-client-content-negotiation-iosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-iosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-iossimulatorarm64/2.3.12/ktor-client-content-negotiation-iossimulatorarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-iossimulatorarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-iossimulatorarm64/2.3.12/ktor-client-content-negotiation-iossimulatorarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-iossimulatorarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-iossimulatorarm64/2.3.12/ktor-client-content-negotiation-iossimulatorarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-iossimulatorarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-iosx64/2.3.12/ktor-client-content-negotiation-iosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-iosx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-iosx64/2.3.12/ktor-client-content-negotiation-iosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-iosx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-iosx64/2.3.12/ktor-client-content-negotiation-iosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-iosx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-js/2.3.12/ktor-client-content-negotiation-js-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-js",
        "version": "2.3.12"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-js/2.3.12/ktor-client-content-negotiation-js-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-js",
        "version": "2.3.12"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-js/2.3.12/ktor-client-content-negotiation-js-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-js",
        "version": "2.3.12"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-jvm/2.3.12/ktor-client-content-negotiation-jvm-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-jvm",
        "version": "2.3.12"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-jvm/2.3.12/ktor-client-content-negotiation-jvm-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-jvm",
        "version": "2.3.12"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-jvm/2.3.12/ktor-client-content-negotiation-jvm-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-jvm",
        "version": "2.3.12"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-linuxarm64/2.3.12/ktor-client-content-negotiation-linuxarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-linuxarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-linuxarm64/2.3.12/ktor-client-content-negotiation-linuxarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-linuxarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-linuxx64/2.3.12/ktor-client-content-negotiation-linuxx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-linuxx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-linuxx64/2.3.12/ktor-client-content-negotiation-linuxx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-linuxx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-macosarm64/2.3.12/ktor-client-content-negotiation-macosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-macosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-macosarm64/2.3.12/ktor-client-content-negotiation-macosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-macosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-macosarm64/2.3.12/ktor-client-content-negotiation-macosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-macosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-macosx64/2.3.12/ktor-client-content-negotiation-macosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-macosx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-macosx64/2.3.12/ktor-client-content-negotiation-macosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-macosx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-macosx64/2.3.12/ktor-client-content-negotiation-macosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-macosx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-mingwx64/2.3.12/ktor-client-content-negotiation-mingwx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-mingwx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-mingwx64/2.3.12/ktor-client-content-negotiation-mingwx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-mingwx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-tvosarm64/2.3.12/ktor-client-content-negotiation-tvosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-tvosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-tvosarm64/2.3.12/ktor-client-content-negotiation-tvosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-tvosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-tvosarm64/2.3.12/ktor-client-content-negotiation-tvosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-tvosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-tvossimulatorarm64/2.3.12/ktor-client-content-negotiation-tvossimulatorarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-tvossimulatorarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-tvossimulatorarm64/2.3.12/ktor-client-content-negotiation-tvossimulatorarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-tvossimulatorarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-tvossimulatorarm64/2.3.12/ktor-client-content-negotiation-tvossimulatorarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-tvossimulatorarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-tvosx64/2.3.12/ktor-client-content-negotiation-tvosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-tvosx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-tvosx64/2.3.12/ktor-client-content-negotiation-tvosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-tvosx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-tvosx64/2.3.12/ktor-client-content-negotiation-tvosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-tvosx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-watchosarm32/2.3.12/ktor-client-content-negotiation-watchosarm32-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-watchosarm32",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-watchosarm32/2.3.12/ktor-client-content-negotiation-watchosarm32-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-watchosarm32",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-watchosarm32/2.3.12/ktor-client-content-negotiation-watchosarm32-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-watchosarm32",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-watchosarm64/2.3.12/ktor-client-content-negotiation-watchosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-watchosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-watchosarm64/2.3.12/ktor-client-content-negotiation-watchosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-watchosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-watchosarm64/2.3.12/ktor-client-content-negotiation-watchosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-watchosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-watchossimulatorarm64/2.3.12/ktor-client-content-negotiation-watchossimulatorarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-watchossimulatorarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-watchossimulatorarm64/2.3.12/ktor-client-content-negotiation-watchossimulatorarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-watchossimulatorarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-watchossimulatorarm64/2.3.12/ktor-client-content-negotiation-watchossimulatorarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-watchossimulatorarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-watchosx64/2.3.12/ktor-client-content-negotiation-watchosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-watchosx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-watchosx64/2.3.12/ktor-client-content-negotiation-watchosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-watchosx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-content-negotiation-watchosx64/2.3.12/ktor-client-content-negotiation-watchosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-content-negotiation-watchosx64",
        "version": "2.3.12"
      }
    }
  ]
}
