{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-http-cio/2.3.12/ktor-http-cio-2.3.12.module",
    "group": "io.ktor",
    "module": "ktor-http-cio",
    "version": "2.3.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.7.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-network",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-http-cio-jvm-2.3.12.jar",
          "url": "ktor-http-cio-jvm-2.3.12.jar",
          "size": 164241,
          "sha512": "3a39b3a4d9231141e96cb0a32776fab5e9c9e51a9f92559ada05cd2f41186dac96db4db1d8bf616c35cff2641382294a4fbb6fdf5e05154ba9a27cd10f11ea81",
          "sha256": "278a5c1662701db9d89f49e74ea77218ed35ad830efffbdf44522ea861477f4b",
          "sha1": "7daa13dd02d96c66580d187b5f47bcf72e072b5d",
          "md5": "2147a372c27296c8e1b55bf981c3ff08"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.7.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-network",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-http-cio-jvm-2.3.12.jar",
          "url": "ktor-http-cio-jvm-2.3.12.jar",
          "size": 164241,
          "sha512": "3a39b3a4d9231141e96cb0a32776fab5e9c9e51a9f92559ada05cd2f41186dac96db4db1d8bf616c35cff2641382294a4fbb6fdf5e05154ba9a27cd10f11ea81",
          "sha256": "278a5c1662701db9d89f49e74ea77218ed35ad830efffbdf44522ea861477f4b",
          "sha1": "7daa13dd02d96c66580d187b5f47bcf72e072b5d",
          "md5": "2147a372c27296c8e1b55bf981c3ff08"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ktor-http-cio-jvm-2.3.12-sources.jar",
          "url": "ktor-http-cio-jvm-2.3.12-sources.jar",
          "size": 27480,
          "sha512": "6678b01ce30c4f8916d28804ca2c2f86239e15baceda24e1c2d013b3ed3b20921af5c4b4d4e3759cab4ce626d0755bd483f3a5238151319db3b2c1ff02363f6d",
          "sha256": "b724df26075cb3dc8a0219d98089844c6f6504a57821a4c60f903d538a9aebf4",
          "sha1": "69974441c4cf84d8ba1ff4addd20794ad629fac2",
          "md5": "7d9a98e3dc5b61283868364c9e077184"
        }
      ]
    }
  ]
}
