version: '3.8'

services:
  # Mock API server
  api:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - ./scripts/mock-api-server.js:/app/server.js:ro
    command: node server.js
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    healthcheck:
      test: [ "CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8080/health" ]
      interval: 5s
      timeout: 3s
      retries: 3

  # Build and test environment
  builder:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      api:
        condition: service_healthy
    environment:
      - GITWRAP_CONFIG=/workspace/test-config.json
      - GIRA_DEBUG=1
    volumes:
      - ./:/workspace
      - gradle-cache:/root/.gradle
    command: |
      sh -c "
        echo 'Waiting for API...' &&
        sleep 2 &&
        echo 'Running integration tests...' &&
        ./scripts/integration-test.sh
      "

  # Interactive development shell
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - api
    environment:
      - GITWRAP_CONFIG=/workspace/test-config.json
      - GIRA_DEBUG=1
    volumes:
      - ./:/workspace
      - gradle-cache:/root/.gradle
    stdin_open: true
    tty: true
    command: /bin/bash

volumes:
  gradle-cache:
