{
  "formatVersion": "1.1",
  "component": {
    "group": "io.ktor",
    "module": "ktor-client-cio",
    "version": "2.3.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-client-core",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http-cio",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-websockets",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-network-tls",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.19.0"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-cio-metadata-2.3.12.jar",
          "url": "ktor-client-cio-2.3.12.jar",
          "size": 13441,
          "sha512": "c0aa0879177d7e90830a400ca26760a20ada19e1b433e2f3452c6c66f7abc7bfa95907be6a1423f44de701f19e61394450d3b2783252d06ec540ace060d0b500",
          "sha256": "bd3ab0fe91652fe28b979c200c8d31ee866ff098fa0f4ab492842227968dffce",
          "sha1": "9072b1405df86c8a5985b07190aa95a29faa6abe",
          "md5": "57beb98f43ff67d0de2e9f4337832970"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "ktor-client-cio-kotlin-2.3.12-sources.jar",
          "url": "ktor-client-cio-2.3.12-sources.jar",
          "size": 15499,
          "sha512": "70b31c578afb743155a4cbf1dac308115aa8583c08e44f77b1ce7a925d168708c9be4028172eb8909029d722a85aebad35e44d4e1662c079e95a7b2b744e9cb6",
          "sha256": "1101363b623c8ce7a300c8c4b3d919b0dd6cc7a87b9c40bcb4b2ab7c553b431d",
          "sha1": "082ac99befa6e0e714ff9e0b6969e1145ffa5774",
          "md5": "73cd58808683f7b680212814e6468ad9"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-iosarm64/2.3.12/ktor-client-cio-iosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-iosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-iosarm64/2.3.12/ktor-client-cio-iosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-iosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-iosarm64/2.3.12/ktor-client-cio-iosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-iosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-iossimulatorarm64/2.3.12/ktor-client-cio-iossimulatorarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-iossimulatorarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-iossimulatorarm64/2.3.12/ktor-client-cio-iossimulatorarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-iossimulatorarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-iossimulatorarm64/2.3.12/ktor-client-cio-iossimulatorarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-iossimulatorarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-iosx64/2.3.12/ktor-client-cio-iosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-iosx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-iosx64/2.3.12/ktor-client-cio-iosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-iosx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-iosx64/2.3.12/ktor-client-cio-iosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-iosx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-client-cio-jvm/2.3.12/ktor-client-cio-jvm-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-jvm",
        "version": "2.3.12"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-client-cio-jvm/2.3.12/ktor-client-cio-jvm-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-jvm",
        "version": "2.3.12"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-client-cio-jvm/2.3.12/ktor-client-cio-jvm-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-jvm",
        "version": "2.3.12"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-linuxarm64/2.3.12/ktor-client-cio-linuxarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-linuxarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-linuxarm64/2.3.12/ktor-client-cio-linuxarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-linuxarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-linuxx64/2.3.12/ktor-client-cio-linuxx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-linuxx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-linuxx64/2.3.12/ktor-client-cio-linuxx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-linuxx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-macosarm64/2.3.12/ktor-client-cio-macosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-macosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-macosarm64/2.3.12/ktor-client-cio-macosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-macosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-macosarm64/2.3.12/ktor-client-cio-macosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-macosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-macosx64/2.3.12/ktor-client-cio-macosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-macosx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-macosx64/2.3.12/ktor-client-cio-macosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-macosx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-macosx64/2.3.12/ktor-client-cio-macosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-macosx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-tvosarm64/2.3.12/ktor-client-cio-tvosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-tvosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-tvosarm64/2.3.12/ktor-client-cio-tvosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-tvosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-tvosarm64/2.3.12/ktor-client-cio-tvosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-tvosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-tvossimulatorarm64/2.3.12/ktor-client-cio-tvossimulatorarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-tvossimulatorarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-tvossimulatorarm64/2.3.12/ktor-client-cio-tvossimulatorarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-tvossimulatorarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-tvossimulatorarm64/2.3.12/ktor-client-cio-tvossimulatorarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-tvossimulatorarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-tvosx64/2.3.12/ktor-client-cio-tvosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-tvosx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-tvosx64/2.3.12/ktor-client-cio-tvosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-tvosx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-tvosx64/2.3.12/ktor-client-cio-tvosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-tvosx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-watchosarm32/2.3.12/ktor-client-cio-watchosarm32-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-watchosarm32",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-watchosarm32/2.3.12/ktor-client-cio-watchosarm32-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-watchosarm32",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-watchosarm32/2.3.12/ktor-client-cio-watchosarm32-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-watchosarm32",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-watchosarm64/2.3.12/ktor-client-cio-watchosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-watchosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-watchosarm64/2.3.12/ktor-client-cio-watchosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-watchosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-watchosarm64/2.3.12/ktor-client-cio-watchosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-watchosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-watchossimulatorarm64/2.3.12/ktor-client-cio-watchossimulatorarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-watchossimulatorarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-watchossimulatorarm64/2.3.12/ktor-client-cio-watchossimulatorarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-watchossimulatorarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-watchossimulatorarm64/2.3.12/ktor-client-cio-watchossimulatorarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-watchossimulatorarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-watchosx64/2.3.12/ktor-client-cio-watchosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-watchosx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-watchosx64/2.3.12/ktor-client-cio-watchosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-watchosx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-cio-watchosx64/2.3.12/ktor-client-cio-watchosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-cio-watchosx64",
        "version": "2.3.12"
      }
    }
  ]
}
