{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlinx-serialization-json/1.7.1/kotlinx-serialization-json-1.7.1.module",
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-json",
    "version": "1.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.7.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-jvm-1.7.1.jar",
          "url": "kotlinx-serialization-json-jvm-1.7.1.jar",
          "size": 270653,
          "sha512": "465b9c05248e9ad359fde9601b992461b8a88a731cdedae54caf0983eb5a2bdf6864c509cddd096505e8192c6a73c40c8e6e54c13445ec68c16276e339424085",
          "sha256": "ab6f1b6e8c70899d8c41f2be5c391d357840f1429b151f4dfb07271029083316",
          "sha1": "c2a4c17f9246285d862cbe1f03d6f8e0848d1958",
          "md5": "3f1263bddd1af097590e36c33a897850"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-bom",
          "version": {
            "requires": "1.7.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-jvm-1.7.1.jar",
          "url": "kotlinx-serialization-json-jvm-1.7.1.jar",
          "size": 270653,
          "sha512": "465b9c05248e9ad359fde9601b992461b8a88a731cdedae54caf0983eb5a2bdf6864c509cddd096505e8192c6a73c40c8e6e54c13445ec68c16276e339424085",
          "sha256": "ab6f1b6e8c70899d8c41f2be5c391d357840f1429b151f4dfb07271029083316",
          "sha1": "c2a4c17f9246285d862cbe1f03d6f8e0848d1958",
          "md5": "3f1263bddd1af097590e36c33a897850"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlinx-serialization-json-jvm-1.7.1-sources.jar",
          "url": "kotlinx-serialization-json-jvm-1.7.1-sources.jar",
          "size": 89677,
          "sha512": "e6637588e2953caceb2efeb2da4dd5519fc8a774582c008d1358ec15f87f8087c59dd58d28d11bd4ca92ccc2345074cc911c938f7ec1fc91bec03636697d4249",
          "sha256": "fd7a94b2156def38a904f35a8bd1084fc8dcd856bc28073d7602eb0f715783f5",
          "sha1": "987307480e0154f5bb7990b71f2eca978912ea8a",
          "md5": "59e2eefe5041eb6f4fafe79e54362ede"
        }
      ]
    }
  ]
}
