{
  "formatVersion": "1.1",
  "component": {
    "url": "../../kotlin-test/2.2.0/kotlin-test-2.2.0.module",
    "group": "org.jetbrains.kotlin",
    "module": "kotlin-test",
    "version": "2.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "jvmJUnit5ApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-api",
          "version": {
            "requires": "5.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-test-junit5-2.2.0.jar",
          "url": "kotlin-test-junit5-2.2.0.jar",
          "size": 5063,
          "sha512": "36b2febdcb61cedec5585240279493aae911490f18bdabe395727076208959fc9e01e1b9b94d4cf6b5da171e2c0db268f1ec6f1d4d8812cec9e544e95b713042",
          "sha256": "716c89ba2e387c4422ea0e9a85c5731f9a328b669a7a0bbed3259e52291b555e",
          "sha1": "7893a671fe85a74292e2fd5c0f60c468b19d6bb1",
          "md5": "2eac01c81861773b4cc85823fd617d37"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-junit5",
          "version": "2.2.0"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-impl",
          "version": "2.2.0"
        }
      ]
    },
    {
      "name": "jvmJUnit5RuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-test",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.junit.jupiter",
          "module": "junit-jupiter-engine",
          "version": {
            "requires": "5.10.1"
          }
        },
        {
          "group": "org.junit.platform",
          "module": "junit-platform-launcher",
          "version": {
            "requires": "1.10.1"
          }
        }
      ],
      "files": [
        {
          "name": "kotlin-test-junit5-2.2.0.jar",
          "url": "kotlin-test-junit5-2.2.0.jar",
          "size": 5063,
          "sha512": "36b2febdcb61cedec5585240279493aae911490f18bdabe395727076208959fc9e01e1b9b94d4cf6b5da171e2c0db268f1ec6f1d4d8812cec9e544e95b713042",
          "sha256": "716c89ba2e387c4422ea0e9a85c5731f9a328b669a7a0bbed3259e52291b555e",
          "sha1": "7893a671fe85a74292e2fd5c0f60c468b19d6bb1",
          "md5": "2eac01c81861773b4cc85823fd617d37"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-junit5",
          "version": "2.2.0"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-impl",
          "version": "2.2.0"
        }
      ]
    },
    {
      "name": "jvmJUnit5SourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "kotlin-test-junit5-2.2.0-sources.jar",
          "url": "kotlin-test-junit5-2.2.0-sources.jar",
          "size": 2850,
          "sha512": "aa488b547a8587cc2cc004a3e943460a043e926a7cb021d70a3182ff05a1e7d542ba77590d9115db58d9ca1c72bf16bca1eb89fe58f46fb5a0fcf6ec2895a22f",
          "sha256": "891c56d8183d2cd3e912cf250adeca889dba51d02b07fce3015321e08f72b4a2",
          "sha1": "e7609990cba72d2a3ce763011ae79e81b9904b51",
          "md5": "6fc43e36017a96bd097f1858ff8fa394"
        }
      ],
      "capabilities": [
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-junit5",
          "version": "2.2.0"
        },
        {
          "group": "org.jetbrains.kotlin",
          "name": "kotlin-test-framework-impl",
          "version": "2.2.0"
        }
      ]
    }
  ]
}