{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-serialization-kotlinx-json/2.3.12/ktor-serialization-kotlinx-json-2.3.12.module",
    "group": "io.ktor",
    "module": "ktor-serialization-kotlinx-json",
    "version": "2.3.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.7.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-serialization-kotlinx-json-jvm-2.3.12.jar",
          "url": "ktor-serialization-kotlinx-json-jvm-2.3.12.jar",
          "size": 24051,
          "sha512": "d9910a757e79d41f89b9ba20931e66074dc93723378926ddc5f6d28ae81722d3cb3f0bb7be63d3a17621a333f1c4a792c083d7d85f309ebae8d297547fd8e6d8",
          "sha256": "4b99f073dd66e7ad43cba60b5259876f85a75e06b84ce9b3b789b9159fb41707",
          "sha1": "117872a523a3cf53df558200678158d21a8208ed",
          "md5": "36e7c9456068ea0ec85daa47074d7418"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.7.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization-kotlinx",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-serialization-kotlinx-json-jvm-2.3.12.jar",
          "url": "ktor-serialization-kotlinx-json-jvm-2.3.12.jar",
          "size": 24051,
          "sha512": "d9910a757e79d41f89b9ba20931e66074dc93723378926ddc5f6d28ae81722d3cb3f0bb7be63d3a17621a333f1c4a792c083d7d85f309ebae8d297547fd8e6d8",
          "sha256": "4b99f073dd66e7ad43cba60b5259876f85a75e06b84ce9b3b789b9159fb41707",
          "sha1": "117872a523a3cf53df558200678158d21a8208ed",
          "md5": "36e7c9456068ea0ec85daa47074d7418"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ktor-serialization-kotlinx-json-jvm-2.3.12-sources.jar",
          "url": "ktor-serialization-kotlinx-json-jvm-2.3.12-sources.jar",
          "size": 5063,
          "sha512": "043021c2024be2dc87c0d5ca56c4ee41967cf3fd20747f18b31a0c14195f2508e62291a512333d252d39c75e515f6e9221e0f458c6458e3b657c965d087921a3",
          "sha256": "132267a83914eb8a34afe69a4171424f35d62efefafa0164bc27e0fe5b4caab6",
          "sha1": "98c15a4d525489c1bf700d8bdebbb289755a7455",
          "md5": "1a92038e35efffef93c45ff15bf715ec"
        }
      ]
    }
  ]
}
