{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-serialization-kotlinx/2.3.12/ktor-serialization-kotlinx-2.3.12.module",
    "group": "io.ktor",
    "module": "ktor-serialization-kotlinx",
    "version": "2.3.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.7.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-serialization-kotlinx-jvm-2.3.12.jar",
          "url": "ktor-serialization-kotlinx-jvm-2.3.12.jar",
          "size": 34503,
          "sha512": "4ec3616505ff5bf50b276701f64fd537e374d4c89d0733b924d4cda17cfa4831c1914f7e360b307010191725109a1e664b5dcc87387f757164a625f3f4d1850b",
          "sha256": "c61427609f5d6f0e398dfbf24a7c9a7dfb4ad590e89f54c5c021cd7c712d4a7f",
          "sha1": "301a562aa286cf23b80831ba599bcb45ad0ba01b",
          "md5": "2907d1acc2d5a51bc5eb88ef6c57d209"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.7.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.5.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-serialization-kotlinx-jvm-2.3.12.jar",
          "url": "ktor-serialization-kotlinx-jvm-2.3.12.jar",
          "size": 34503,
          "sha512": "4ec3616505ff5bf50b276701f64fd537e374d4c89d0733b924d4cda17cfa4831c1914f7e360b307010191725109a1e664b5dcc87387f757164a625f3f4d1850b",
          "sha256": "c61427609f5d6f0e398dfbf24a7c9a7dfb4ad590e89f54c5c021cd7c712d4a7f",
          "sha1": "301a562aa286cf23b80831ba599bcb45ad0ba01b",
          "md5": "2907d1acc2d5a51bc5eb88ef6c57d209"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ktor-serialization-kotlinx-jvm-2.3.12-sources.jar",
          "url": "ktor-serialization-kotlinx-jvm-2.3.12-sources.jar",
          "size": 6610,
          "sha512": "42159b08ff194462f0f4f4acfcb18300ce19db8520e518ad595d63c2395dcc2bcf5a70b55b8e67ddb1ab35a44de0b122ec99ba082a9890bda57b0f8b1e985815",
          "sha256": "169c88f013c708bbb5c54605d011322f6da28b2c353af17eb62b132d0c585ffb",
          "sha1": "6e2031a6ce2b0695b57966b4f1dffecaf0ecad63",
          "md5": "275ec5556ceb716e2644fec48c048574"
        }
      ]
    }
  ]
}
