{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-serialization-json",
    "version": "1.7.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "2.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.0.0"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-serialization-json-metadata-1.7.1.jar",
          "url": "kotlinx-serialization-json-1.7.1.jar",
          "size": 42796,
          "sha512": "64cf46cef033ed640b633ec45062298ee65fe92d525c0220c5fbd246b3edff80a6e91f41191a84a216d1188a8bd8f2d69fd510553b617e122a20942506207b5b",
          "sha256": "8a5dacc3db31d698079e3d5a3a80c6533a7d906c2fa768e709ab5943200f5572",
          "sha1": "31ccf41f6dd470fad424346b8c25f48a68bcca1c",
          "md5": "842dfa85c1d71b1c0c8785870628a6f4"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "kotlinx-serialization-json-kotlin-1.7.1-sources.jar",
          "url": "kotlinx-serialization-json-1.7.1-sources.jar",
          "size": 85976,
          "sha512": "eea4913a0dd4f829c0cb4dacdb5ed7b1fd65c77ef84af566747f92b979d4662a1b6976943482e1b00b49eb25ad7ff101c0bbcfa2560480b970da45a3c25c9df2",
          "sha256": "210c139ddd7939359c524b343d8c3027150b770f3bab3a487d6a4400ce2e7959",
          "sha1": "ba93aedcb01cb218e3b5e9ca262dc1191e36ef9e",
          "md5": "526eae06279cac5f303bcb816da6d938"
        }
      ]
    },
    {
      "name": "androidNativeArm32ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-androidnativearm32/1.7.1/kotlinx-serialization-json-androidnativearm32-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-androidnativearm32",
        "version": "1.7.1"
      }
    },
    {
      "name": "androidNativeArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-androidnativearm32/1.7.1/kotlinx-serialization-json-androidnativearm32-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-androidnativearm32",
        "version": "1.7.1"
      }
    },
    {
      "name": "androidNativeArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-androidnativearm64/1.7.1/kotlinx-serialization-json-androidnativearm64-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-androidnativearm64",
        "version": "1.7.1"
      }
    },
    {
      "name": "androidNativeArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-androidnativearm64/1.7.1/kotlinx-serialization-json-androidnativearm64-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-androidnativearm64",
        "version": "1.7.1"
      }
    },
    {
      "name": "androidNativeX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-androidnativex64/1.7.1/kotlinx-serialization-json-androidnativex64-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-androidnativex64",
        "version": "1.7.1"
      }
    },
    {
      "name": "androidNativeX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-androidnativex64/1.7.1/kotlinx-serialization-json-androidnativex64-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-androidnativex64",
        "version": "1.7.1"
      }
    },
    {
      "name": "androidNativeX86ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-androidnativex86/1.7.1/kotlinx-serialization-json-androidnativex86-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-androidnativex86",
        "version": "1.7.1"
      }
    },
    {
      "name": "androidNativeX86SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "android_x86",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-androidnativex86/1.7.1/kotlinx-serialization-json-androidnativex86-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-androidnativex86",
        "version": "1.7.1"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-iosarm64/1.7.1/kotlinx-serialization-json-iosarm64-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-iosarm64",
        "version": "1.7.1"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-iosarm64/1.7.1/kotlinx-serialization-json-iosarm64-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-iosarm64",
        "version": "1.7.1"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-iosarm64/1.7.1/kotlinx-serialization-json-iosarm64-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-iosarm64",
        "version": "1.7.1"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-iossimulatorarm64/1.7.1/kotlinx-serialization-json-iossimulatorarm64-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-iossimulatorarm64",
        "version": "1.7.1"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-iossimulatorarm64/1.7.1/kotlinx-serialization-json-iossimulatorarm64-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-iossimulatorarm64",
        "version": "1.7.1"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-iossimulatorarm64/1.7.1/kotlinx-serialization-json-iossimulatorarm64-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-iossimulatorarm64",
        "version": "1.7.1"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-iosx64/1.7.1/kotlinx-serialization-json-iosx64-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-iosx64",
        "version": "1.7.1"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-iosx64/1.7.1/kotlinx-serialization-json-iosx64-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-iosx64",
        "version": "1.7.1"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-iosx64/1.7.1/kotlinx-serialization-json-iosx64-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-iosx64",
        "version": "1.7.1"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-js/1.7.1/kotlinx-serialization-json-js-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-js",
        "version": "1.7.1"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-js/1.7.1/kotlinx-serialization-json-js-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-js",
        "version": "1.7.1"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-js/1.7.1/kotlinx-serialization-json-js-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-js",
        "version": "1.7.1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-jvm/1.7.1/kotlinx-serialization-json-jvm-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-jvm",
        "version": "1.7.1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-jvm/1.7.1/kotlinx-serialization-json-jvm-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-jvm",
        "version": "1.7.1"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-jvm/1.7.1/kotlinx-serialization-json-jvm-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-jvm",
        "version": "1.7.1"
      }
    },
    {
      "name": "linuxArm32HfpApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-linuxarm32hfp/1.7.1/kotlinx-serialization-json-linuxarm32hfp-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-linuxarm32hfp",
        "version": "1.7.1"
      }
    },
    {
      "name": "linuxArm32HfpSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm32_hfp",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-linuxarm32hfp/1.7.1/kotlinx-serialization-json-linuxarm32hfp-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-linuxarm32hfp",
        "version": "1.7.1"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-linuxarm64/1.7.1/kotlinx-serialization-json-linuxarm64-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-linuxarm64",
        "version": "1.7.1"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-linuxarm64/1.7.1/kotlinx-serialization-json-linuxarm64-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-linuxarm64",
        "version": "1.7.1"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-linuxx64/1.7.1/kotlinx-serialization-json-linuxx64-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-linuxx64",
        "version": "1.7.1"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-linuxx64/1.7.1/kotlinx-serialization-json-linuxx64-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-linuxx64",
        "version": "1.7.1"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-macosarm64/1.7.1/kotlinx-serialization-json-macosarm64-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-macosarm64",
        "version": "1.7.1"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-macosarm64/1.7.1/kotlinx-serialization-json-macosarm64-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-macosarm64",
        "version": "1.7.1"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-macosarm64/1.7.1/kotlinx-serialization-json-macosarm64-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-macosarm64",
        "version": "1.7.1"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-macosx64/1.7.1/kotlinx-serialization-json-macosx64-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-macosx64",
        "version": "1.7.1"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-macosx64/1.7.1/kotlinx-serialization-json-macosx64-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-macosx64",
        "version": "1.7.1"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-macosx64/1.7.1/kotlinx-serialization-json-macosx64-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-macosx64",
        "version": "1.7.1"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-mingwx64/1.7.1/kotlinx-serialization-json-mingwx64-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-mingwx64",
        "version": "1.7.1"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-mingwx64/1.7.1/kotlinx-serialization-json-mingwx64-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-mingwx64",
        "version": "1.7.1"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-tvosarm64/1.7.1/kotlinx-serialization-json-tvosarm64-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-tvosarm64",
        "version": "1.7.1"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-tvosarm64/1.7.1/kotlinx-serialization-json-tvosarm64-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-tvosarm64",
        "version": "1.7.1"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-tvosarm64/1.7.1/kotlinx-serialization-json-tvosarm64-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-tvosarm64",
        "version": "1.7.1"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-tvossimulatorarm64/1.7.1/kotlinx-serialization-json-tvossimulatorarm64-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-tvossimulatorarm64",
        "version": "1.7.1"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-tvossimulatorarm64/1.7.1/kotlinx-serialization-json-tvossimulatorarm64-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-tvossimulatorarm64",
        "version": "1.7.1"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-tvossimulatorarm64/1.7.1/kotlinx-serialization-json-tvossimulatorarm64-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-tvossimulatorarm64",
        "version": "1.7.1"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-tvosx64/1.7.1/kotlinx-serialization-json-tvosx64-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-tvosx64",
        "version": "1.7.1"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-tvosx64/1.7.1/kotlinx-serialization-json-tvosx64-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-tvosx64",
        "version": "1.7.1"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-tvosx64/1.7.1/kotlinx-serialization-json-tvosx64-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-tvosx64",
        "version": "1.7.1"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-wasm-js/1.7.1/kotlinx-serialization-json-wasm-js-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-wasm-js",
        "version": "1.7.1"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-wasm-js/1.7.1/kotlinx-serialization-json-wasm-js-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-wasm-js",
        "version": "1.7.1"
      }
    },
    {
      "name": "wasmJsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-wasm-js/1.7.1/kotlinx-serialization-json-wasm-js-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-wasm-js",
        "version": "1.7.1"
      }
    },
    {
      "name": "wasmWasiApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-wasm-wasi/1.7.1/kotlinx-serialization-json-wasm-wasi-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-wasm-wasi",
        "version": "1.7.1"
      }
    },
    {
      "name": "wasmWasiRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-wasm-wasi/1.7.1/kotlinx-serialization-json-wasm-wasi-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-wasm-wasi",
        "version": "1.7.1"
      }
    },
    {
      "name": "wasmWasiSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-wasm-wasi/1.7.1/kotlinx-serialization-json-wasm-wasi-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-wasm-wasi",
        "version": "1.7.1"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-watchosarm32/1.7.1/kotlinx-serialization-json-watchosarm32-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-watchosarm32",
        "version": "1.7.1"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-watchosarm32/1.7.1/kotlinx-serialization-json-watchosarm32-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-watchosarm32",
        "version": "1.7.1"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-watchosarm32/1.7.1/kotlinx-serialization-json-watchosarm32-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-watchosarm32",
        "version": "1.7.1"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-watchosarm64/1.7.1/kotlinx-serialization-json-watchosarm64-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-watchosarm64",
        "version": "1.7.1"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-watchosarm64/1.7.1/kotlinx-serialization-json-watchosarm64-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-watchosarm64",
        "version": "1.7.1"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-watchosarm64/1.7.1/kotlinx-serialization-json-watchosarm64-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-watchosarm64",
        "version": "1.7.1"
      }
    },
    {
      "name": "watchosDeviceArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-watchosdevicearm64/1.7.1/kotlinx-serialization-json-watchosdevicearm64-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-watchosdevicearm64",
        "version": "1.7.1"
      }
    },
    {
      "name": "watchosDeviceArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-watchosdevicearm64/1.7.1/kotlinx-serialization-json-watchosdevicearm64-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-watchosdevicearm64",
        "version": "1.7.1"
      }
    },
    {
      "name": "watchosDeviceArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_device_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-watchosdevicearm64/1.7.1/kotlinx-serialization-json-watchosdevicearm64-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-watchosdevicearm64",
        "version": "1.7.1"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-watchossimulatorarm64/1.7.1/kotlinx-serialization-json-watchossimulatorarm64-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-watchossimulatorarm64",
        "version": "1.7.1"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-watchossimulatorarm64/1.7.1/kotlinx-serialization-json-watchossimulatorarm64-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-watchossimulatorarm64",
        "version": "1.7.1"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-watchossimulatorarm64/1.7.1/kotlinx-serialization-json-watchossimulatorarm64-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-watchossimulatorarm64",
        "version": "1.7.1"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-watchosx64/1.7.1/kotlinx-serialization-json-watchosx64-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-watchosx64",
        "version": "1.7.1"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-watchosx64/1.7.1/kotlinx-serialization-json-watchosx64-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-watchosx64",
        "version": "1.7.1"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../kotlinx-serialization-json-watchosx64/1.7.1/kotlinx-serialization-json-watchosx64-1.7.1.module",
        "group": "org.jetbrains.kotlinx",
        "module": "kotlinx-serialization-json-watchosx64",
        "version": "1.7.1"
      }
    }
  ]
}
