{
  "formatVersion": "1.1",
  "component": {
    "group": "io.ktor",
    "module": "ktor-websocket-serialization",
    "version": "2.3.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-serialization",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.19.0"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-websocket-serialization-metadata-2.3.12.jar",
          "url": "ktor-websocket-serialization-2.3.12.jar",
          "size": 4390,
          "sha512": "f19b1ed2a16651b1c7afb0418a6fbb18ab6967192699a65c0c958389c186062982a180659076f058b8525ea7cfb28806635ca7a9ab4ab290bd6ee2e0c62d61d7",
          "sha256": "242130c209c32282d9f20ec49e57d74818a1a728800ecd902deeddcf051180c5",
          "sha1": "59f3fb094f9471b70882f5d78ebf167f88e78ccd",
          "md5": "c96412de2bef4cb98ad2e664e81a8624"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "ktor-websocket-serialization-kotlin-2.3.12-sources.jar",
          "url": "ktor-websocket-serialization-2.3.12-sources.jar",
          "size": 2273,
          "sha512": "f9e832c06ecf7c543ef6fc5351dfc1cc72ab5fb4289de8120697333c10d4e96ae3efb7cea9db0ff6c473a388acd939b3ef1e111a5c4b4d8d2c5306000cad388e",
          "sha256": "b135316b2dcea4bbf2e4986a0513ee3c838a30d77b06d6b4043e404dd4261045",
          "sha1": "cbef7bd8f02f3ab747e6cb3904e33a42ed743b36",
          "md5": "d63058a06a025861945b82097aa19df7"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-websocket-serialization-iosarm64/2.3.12/ktor-websocket-serialization-iosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-websocket-serialization-iosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-websocket-serialization-iosarm64/2.3.12/ktor-websocket-serialization-iosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-websocket-serialization-iosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-websocket-serialization-iosarm64/2.3.12/ktor-websocket-serialization-iosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-websocket-serialization-iosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-websocket-serialization-iossimulatorarm64/2.3.12/ktor-websocket-serialization-iossimulatorarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-websocket-serialization-iossimulatorarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-websocket-serialization-iossimulatorarm64/2.3.12/ktor-websocket-serialization-iossimulatorarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-websocket-serialization-iossimulatorarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-websocket-serialization-iossimulatorarm64/2.3.12/ktor-websocket-serialization-iossimulatorarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-websocket-serialization-iossimulatorarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-websocket-serialization-iosx64/2.3.12/ktor-websocket-serialization-iosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-websocket-serialization-iosx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-websocket-serialization-iosx64/2.3.12/ktor-websocket-serialization-iosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-websocket-serialization-iosx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-websocket-serialization-iosx64/2.3.12/ktor-websocket-serialization-iosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-websocket-serialization-iosx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktor-websocket-serialization-js/2.3.12/ktor-websocket-serialization-js-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-websocket-serialization-js",
        "version": "2.3.12"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktor-websocket-serialization-js/2.3.12/ktor-websocket-serialization-js-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-websocket-serialization-js",
        "version": "2.3.12"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktor-websocket-serialization-js/2.3.12/ktor-websocket-serialization-js-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-websocket-serialization-js",
        "version": "2.3.12"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-websocket-serialization-jvm/2.3.12/ktor-websocket-serialization-jvm-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-websocket-serialization-jvm",
        "version": "2.3.12"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-websocket-serialization-jvm/2.3.12/ktor-websocket-serialization-jvm-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-websocket-serialization-jvm",
        "version": "2.3.12"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-websocket-serialization-jvm/2.3.12/ktor-websocket-serialization-jvm-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-websocket-serialization-jvm",
        "version": "2.3.12"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-websocket-serialization-linuxarm64/2.3.12/ktor-websocket-serialization-linuxarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-websocket-serialization-linuxarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-websocket-serialization-linuxarm64/2.3.12/ktor-websocket-serialization-linuxarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-websocket-serialization-linuxarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-websocket-serialization-linuxx64/2.3.12/ktor-websocket-serialization-linuxx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-websocket-serialization-linuxx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-websocket-serialization-linuxx64/2.3.12/ktor-websocket-serialization-linuxx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-websocket-serialization-linuxx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-websocket-serialization-macosarm64/2.3.12/ktor-websocket-serialization-macosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-websocket-serialization-macosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-websocket-serialization-macosarm64/2.3.12/ktor-websocket-serialization-macosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-websocket-serialization-macosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-websocket-serialization-macosarm64/2.3.12/ktor-websocket-serialization-macosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-websocket-serialization-macosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-websocket-serialization-macosx64/2.3.12/ktor-websocket-serialization-macosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-websocket-serialization-macosx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-websocket-serialization-macosx64/2.3.12/ktor-websocket-serialization-macosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-websocket-serialization-macosx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-websocket-serialization-macosx64/2.3.12/ktor-websocket-serialization-macosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-websocket-serialization-macosx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-websocket-serialization-mingwx64/2.3.12/ktor-websocket-serialization-mingwx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-websocket-serialization-mingwx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-websocket-serialization-mingwx64/2.3.12/ktor-websocket-serialization-mingwx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-websocket-serialization-mingwx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-websocket-serialization-tvosarm64/2.3.12/ktor-websocket-serialization-tvosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-websocket-serialization-tvosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-websocket-serialization-tvosarm64/2.3.12/ktor-websocket-serialization-tvosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-websocket-serialization-tvosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-websocket-serialization-tvosarm64/2.3.12/ktor-websocket-serialization-tvosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-websocket-serialization-tvosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-websocket-serialization-tvossimulatorarm64/2.3.12/ktor-websocket-serialization-tvossimulatorarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-websocket-serialization-tvossimulatorarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-websocket-serialization-tvossimulatorarm64/2.3.12/ktor-websocket-serialization-tvossimulatorarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-websocket-serialization-tvossimulatorarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-websocket-serialization-tvossimulatorarm64/2.3.12/ktor-websocket-serialization-tvossimulatorarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-websocket-serialization-tvossimulatorarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-websocket-serialization-tvosx64/2.3.12/ktor-websocket-serialization-tvosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-websocket-serialization-tvosx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-websocket-serialization-tvosx64/2.3.12/ktor-websocket-serialization-tvosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-websocket-serialization-tvosx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-websocket-serialization-tvosx64/2.3.12/ktor-websocket-serialization-tvosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-websocket-serialization-tvosx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-websocket-serialization-watchosarm32/2.3.12/ktor-websocket-serialization-watchosarm32-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-websocket-serialization-watchosarm32",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-websocket-serialization-watchosarm32/2.3.12/ktor-websocket-serialization-watchosarm32-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-websocket-serialization-watchosarm32",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-websocket-serialization-watchosarm32/2.3.12/ktor-websocket-serialization-watchosarm32-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-websocket-serialization-watchosarm32",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-websocket-serialization-watchosarm64/2.3.12/ktor-websocket-serialization-watchosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-websocket-serialization-watchosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-websocket-serialization-watchosarm64/2.3.12/ktor-websocket-serialization-watchosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-websocket-serialization-watchosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-websocket-serialization-watchosarm64/2.3.12/ktor-websocket-serialization-watchosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-websocket-serialization-watchosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-websocket-serialization-watchossimulatorarm64/2.3.12/ktor-websocket-serialization-watchossimulatorarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-websocket-serialization-watchossimulatorarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-websocket-serialization-watchossimulatorarm64/2.3.12/ktor-websocket-serialization-watchossimulatorarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-websocket-serialization-watchossimulatorarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-websocket-serialization-watchossimulatorarm64/2.3.12/ktor-websocket-serialization-watchossimulatorarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-websocket-serialization-watchossimulatorarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-websocket-serialization-watchosx64/2.3.12/ktor-websocket-serialization-watchosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-websocket-serialization-watchosx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-websocket-serialization-watchosx64/2.3.12/ktor-websocket-serialization-watchosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-websocket-serialization-watchosx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-websocket-serialization-watchosx64/2.3.12/ktor-websocket-serialization-watchosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-websocket-serialization-watchosx64",
        "version": "2.3.12"
      }
    }
  ]
}
