{
  "formatVersion": "1.1",
  "component": {
    "url": "../../ktor-http/2.3.12/ktor-http-2.3.12.module",
    "group": "io.ktor",
    "module": "ktor-http",
    "version": "2.3.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.7.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-http-jvm-2.3.12.jar",
          "url": "ktor-http-jvm-2.3.12.jar",
          "size": 414683,
          "sha512": "ecb91d7a75959181a7a4a276b1892a375f35baace9a44b52a53ad1e0911b6337bb8a7138414f606462efd5ed2ecc62c345dfe8c768585e00106df919eaf6dc17",
          "sha256": "907111c439b3bd4433d2debb687920d5f8df8c6229b68ed540805d5e3763b6a8",
          "sha1": "2f3ac4d5a075b69fcd57073b8cd4fdfb725f1e00",
          "md5": "9596dc065bb42b0bdbc9cc97c078ad71"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-jdk8",
          "version": {
            "requires": "1.7.1"
          },
          "excludes": [
            {
              "group": "*",
              "module": "kotlin-stdlib-jvm"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk8"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib-jdk7"
            },
            {
              "group": "*",
              "module": "kotlin-stdlib"
            }
          ]
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.36"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-utils",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-http-jvm-2.3.12.jar",
          "url": "ktor-http-jvm-2.3.12.jar",
          "size": 414683,
          "sha512": "ecb91d7a75959181a7a4a276b1892a375f35baace9a44b52a53ad1e0911b6337bb8a7138414f606462efd5ed2ecc62c345dfe8c768585e00106df919eaf6dc17",
          "sha256": "907111c439b3bd4433d2debb687920d5f8df8c6229b68ed540805d5e3763b6a8",
          "sha1": "2f3ac4d5a075b69fcd57073b8cd4fdfb725f1e00",
          "md5": "9596dc065bb42b0bdbc9cc97c078ad71"
        }
      ]
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "ktor-http-jvm-2.3.12-sources.jar",
          "url": "ktor-http-jvm-2.3.12-sources.jar",
          "size": 86130,
          "sha512": "61a0bd3ec90c68d1c06381c1c5b418cc1be9cb21e71ba22340bfaedaf0605ca8d2d0ae90c126a42ba80b6da83787c9db32b7c4f7f9dc40b89281452288ce9cb2",
          "sha256": "9438da19c45c5a60a2653c705d1948ba2e346d3d450599b57bda9827649c8277",
          "sha1": "e9f3b639ba55b661eaedacea75f7ce8856f859b6",
          "md5": "854030b25d94d19afd6d9b58d4077a41"
        }
      ]
    }
  ]
}
