{
  "formatVersion": "1.1",
  "component": {
    "group": "io.ktor",
    "module": "ktor-client-core",
    "version": "2.3.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.7"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.7.1"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-http",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-events",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "io.ktor",
          "module": "ktor-websocket-serialization",
          "version": {
            "requires": "2.3.12"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.8.22"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "atomicfu",
          "version": {
            "requires": "0.19.0"
          }
        }
      ],
      "files": [
        {
          "name": "ktor-client-core-metadata-2.3.12.jar",
          "url": "ktor-client-core-2.3.12.jar",
          "size": 58970,
          "sha512": "37af55d9adba953c6e09988a0fe0d9afbb8930efb52c0c011aaea062e4c1594a60e14d64ebafa96bf6f1c0478db8021002a08e69a7517ef1a884bc8179811562",
          "sha256": "13f9d5ec238aa8da17f2c080500d068a963a38a31a16415097b840e5f8c3bff6",
          "sha1": "b4f75ab2bce9d3788efdeb557a39611f072f7a4b",
          "md5": "1ac8c8b8e3e20de8dd4e1b83c838a11a"
        }
      ]
    },
    {
      "name": "metadataSourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "ktor-client-core-kotlin-2.3.12-sources.jar",
          "url": "ktor-client-core-2.3.12-sources.jar",
          "size": 103559,
          "sha512": "198f29ed507f21b729dd2a7996fc11e2250a775ebad504f450014b6a51ea21992784162ad7cb6e816e93cfc26bd66d09fa92d80162e700f995637c2191a02f02",
          "sha256": "1535d4e2e0f3e72364d2e49b31519a0f11c9298e2e55b4a78514c8fe28ae9587",
          "sha1": "e395ae26f73172f8f0957624f857e704fc34bfa0",
          "md5": "8015b0f681fa13694f3d999b7b56b045"
        }
      ]
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-iosarm64/2.3.12/ktor-client-core-iosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-core-iosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-iosarm64/2.3.12/ktor-client-core-iosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-core-iosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "iosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-iosarm64/2.3.12/ktor-client-core-iosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-core-iosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-iossimulatorarm64/2.3.12/ktor-client-core-iossimulatorarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-core-iossimulatorarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-iossimulatorarm64/2.3.12/ktor-client-core-iossimulatorarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-core-iossimulatorarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "iosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-iossimulatorarm64/2.3.12/ktor-client-core-iossimulatorarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-core-iossimulatorarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "iosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-iosx64/2.3.12/ktor-client-core-iosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-core-iosx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "iosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-iosx64/2.3.12/ktor-client-core-iosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-core-iosx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "iosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "ios_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-iosx64/2.3.12/ktor-client-core-iosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-core-iosx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "jsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktor-client-core-js/2.3.12/ktor-client-core-js-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-core-js",
        "version": "2.3.12"
      }
    },
    {
      "name": "jsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktor-client-core-js/2.3.12/ktor-client-core-js-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-core-js",
        "version": "2.3.12"
      }
    },
    {
      "name": "jsSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../ktor-client-core-js/2.3.12/ktor-client-core-js-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-core-js",
        "version": "2.3.12"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-client-core-jvm/2.3.12/ktor-client-core-jvm-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-core-jvm",
        "version": "2.3.12"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-client-core-jvm/2.3.12/ktor-client-core-jvm-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-core-jvm",
        "version": "2.3.12"
      }
    },
    {
      "name": "jvmSourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../ktor-client-core-jvm/2.3.12/ktor-client-core-jvm-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-core-jvm",
        "version": "2.3.12"
      }
    },
    {
      "name": "linuxArm64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-linuxarm64/2.3.12/ktor-client-core-linuxarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-core-linuxarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "linuxArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-linuxarm64/2.3.12/ktor-client-core-linuxarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-core-linuxarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "linuxX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-linuxx64/2.3.12/ktor-client-core-linuxx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-core-linuxx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "linuxX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "linux_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-linuxx64/2.3.12/ktor-client-core-linuxx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-core-linuxx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "macosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-macosarm64/2.3.12/ktor-client-core-macosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-core-macosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "macosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-macosarm64/2.3.12/ktor-client-core-macosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-core-macosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "macosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-macosarm64/2.3.12/ktor-client-core-macosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-core-macosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "macosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-macosx64/2.3.12/ktor-client-core-macosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-core-macosx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "macosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-macosx64/2.3.12/ktor-client-core-macosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-core-macosx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "macosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "macos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-macosx64/2.3.12/ktor-client-core-macosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-core-macosx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "mingwX64ApiElements-published",
      "attributes": {
        "artifactType": "org.jetbrains.kotlin.klib",
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-mingwx64/2.3.12/ktor-client-core-mingwx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-core-mingwx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "mingwX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "mingw_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-mingwx64/2.3.12/ktor-client-core-mingwx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-core-mingwx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "tvosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-tvosarm64/2.3.12/ktor-client-core-tvosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-core-tvosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "tvosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-tvosarm64/2.3.12/ktor-client-core-tvosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-core-tvosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "tvosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-tvosarm64/2.3.12/ktor-client-core-tvosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-core-tvosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "tvosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-tvossimulatorarm64/2.3.12/ktor-client-core-tvossimulatorarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-core-tvossimulatorarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "tvosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-tvossimulatorarm64/2.3.12/ktor-client-core-tvossimulatorarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-core-tvossimulatorarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "tvosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-tvossimulatorarm64/2.3.12/ktor-client-core-tvossimulatorarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-core-tvossimulatorarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "tvosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-tvosx64/2.3.12/ktor-client-core-tvosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-core-tvosx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "tvosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-tvosx64/2.3.12/ktor-client-core-tvosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-core-tvosx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "tvosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "tvos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-tvosx64/2.3.12/ktor-client-core-tvosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-core-tvosx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosArm32ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-watchosarm32/2.3.12/ktor-client-core-watchosarm32-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-core-watchosarm32",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosArm32MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-watchosarm32/2.3.12/ktor-client-core-watchosarm32-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-core-watchosarm32",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosArm32SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm32",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-watchosarm32/2.3.12/ktor-client-core-watchosarm32-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-core-watchosarm32",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-watchosarm64/2.3.12/ktor-client-core-watchosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-core-watchosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-watchosarm64/2.3.12/ktor-client-core-watchosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-core-watchosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-watchosarm64/2.3.12/ktor-client-core-watchosarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-core-watchosarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-watchossimulatorarm64/2.3.12/ktor-client-core-watchossimulatorarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-core-watchossimulatorarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-watchossimulatorarm64/2.3.12/ktor-client-core-watchossimulatorarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-core-watchossimulatorarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosSimulatorArm64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-watchossimulatorarm64/2.3.12/ktor-client-core-watchossimulatorarm64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-core-watchossimulatorarm64",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosX64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-watchosx64/2.3.12/ktor-client-core-watchosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-core-watchosx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosX64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-watchosx64/2.3.12/ktor-client-core-watchosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-core-watchosx64",
        "version": "2.3.12"
      }
    },
    {
      "name": "watchosX64SourcesElements-published",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.native.target": "watchos_x64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../ktor-client-core-watchosx64/2.3.12/ktor-client-core-watchosx64-2.3.12.module",
        "group": "io.ktor",
        "module": "ktor-client-core-watchosx64",
        "version": "2.3.12"
      }
    }
  ]
}
