name: Build and Release

on:
  push:
    branches: [ main, develop ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Test
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up GraalVM 21
        uses: actions/setup-java@v4
        with:
          distribution: graalvm
          java-version: '21'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew test --no-daemon

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-results
          path: '**/build/test-results/test/*.xml'

  package:
    name: Build Artifacts
    needs: test
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up GraalVM 21
        uses: actions/setup-java@v4
        with:
          distribution: graalvm
          java-version: '21'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build artifacts
        run: |
          ./gradlew :cli:nativeCompile --no-daemon
          mkdir -p dist
          cp cli/build/native/nativeCompile/kapture dist/kapture-linux-x64
          chmod +x dist/kapture-linux-x64
          (cd dist && sha256sum kapture-linux-x64 > kapture-linux-x64.sha256)

      - name: Upload distribution artifact
        uses: actions/upload-artifact@v4
        with:
          name: kapture-distribution
          path: dist

  release:
    name: Publish Release
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    needs: package
    runs-on: ubuntu-22.04

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: kapture-distribution
          path: dist

      - name: Publish GitHub release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/kapture-linux-x64
            dist/kapture-linux-x64.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
